// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReactSimplemdeEditor = require("react-simplemde-editor");

function make(id, label, value, onChange, options, events, children) {
  var tmp = { };
  if (id) {
    tmp.id = id[0];
  }
  if (label) {
    tmp.label = label[0];
  }
  if (value) {
    tmp.value = value[0];
  }
  if (onChange) {
    tmp.onChange = onChange[0];
  }
  if (options) {
    tmp.options = options[0];
  }
  if (events) {
    tmp.events = events[0];
  }
  return ReasonReact.wrapJsForReason(ReactSimplemdeEditor, tmp, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
